GET http://localhost:8000/test

###

POST http://localhost:8000/test
{
  'test'
}

###
POST http://192.168.45.98:8888/api/user
Content-Type: application/json
{
   "username" : "zacharie.millet",
   "password" : ""

}

###


